version: '3'

services:
  srv:
    container_name: situman-srv
    image: situman-srv
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS=redis://db:6379
      - ADMIN=yesiam
    ports:
      - 1112:3000
    restart: always
  db:
    container_name: situman-db
    image: redis:6.0-alpine
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    name: situman
    
  